# Generated by Django 5.2.7 on 2025-11-23 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('group_invite', 'Invitación a Grupo'), ('join_request', 'Solicitud de Ingreso'), ('request_approved', 'Solicitud Aprobada'), ('request_rejected', 'Solicitud Rechazada'), ('member_promoted', 'Promoción de Rol'), ('member_demoted', 'Degradación de Rol'), ('member_removed', 'Expulsado del Grupo'), ('member_banned', 'Baneado del Grupo'), ('member_unbanned', 'Desbaneado del Grupo'), ('task_assigned', 'Tarea Asignada'), ('task_completed', 'Tarea Completada'), ('task_reminder', 'Recordatorio de Tarea'), ('event_reminder', 'Recordatorio de Evento'), ('subject_added', 'Materia Agregada'), ('general', 'General')], max_length=30),
        ),
    ]
