# Generated by Django 5.2.7 on 2025-11-23 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('groups', '0002_alter_groupactivity_activity_type_banneduser'),
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('member_joined', 'Miembro se unió'), ('member_left', 'Miembro salió'), ('member_removed', 'Miembro expulsado'), ('member_approved', 'Miembro aprobado'), ('member_rejected', 'Solicitud rechazada'), ('role_changed', 'Rol cambiado'), ('permissions_changed', 'Permisos modificados'), ('group_created', 'Grupo creado'), ('group_updated', 'Grupo actualizado'), ('subject_added', 'Materia agregada'), ('subject_removed', 'Materia eliminada')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('description', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('affected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affected_by_actions', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_log', to='groups.group')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_actions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de Grupo',
                'verbose_name_plural': 'Actividades de Grupo',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='RevertibleAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('task_edit', 'Edición de tarea'), ('task_delete', 'Eliminación de tarea'), ('member_remove', 'Expulsión de miembro'), ('permission_change', 'Cambio de permisos')], max_length=30)),
                ('status', models.CharField(choices=[('active', 'Activa'), ('reverted', 'Revertida'), ('expired', 'Expirada')], default='active', max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('reverted_at', models.DateTimeField(blank=True, null=True)),
                ('snapshot_data', models.JSONField()),
                ('affected_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='affected_actions', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='groups.group')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='performed_actions', to=settings.AUTH_USER_MODEL)),
                ('reverted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reverted_actions', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
            ],
            options={
                'verbose_name': 'Acción Revertible',
                'verbose_name_plural': 'Acciones Revertibles',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='TaskHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_title', models.CharField(max_length=200)),
                ('action', models.CharField(choices=[('created', 'Creada'), ('edited', 'Editada'), ('deleted', 'Eliminada'), ('completed', 'Completada'), ('reopened', 'Reabierta')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('field_changed', models.CharField(blank=True, max_length=100)),
                ('old_value', models.TextField(blank=True)),
                ('new_value', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_history', to='groups.group')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='history', to='tasks.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Historial de Tarea',
                'verbose_name_plural': 'Historial de Tareas',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('login', 'Inicio de sesión'), ('logout', 'Cierre de sesión'), ('task_create', 'Crear tarea'), ('task_edit', 'Editar tarea'), ('task_delete', 'Eliminar tarea'), ('task_complete', 'Completar tarea'), ('group_create', 'Crear grupo'), ('group_join', 'Unirse a grupo'), ('group_leave', 'Salir de grupo'), ('subject_create', 'Crear materia'), ('subject_delete', 'Eliminar materia'), ('permission_change', 'Cambiar permisos'), ('member_remove', 'Expulsar miembro')], max_length=30)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=255)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='groups.group')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tasks.task')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Log de Acción',
                'verbose_name_plural': 'Logs de Acciones',
                'ordering': ['-timestamp'],
            },
        ),
    ]
