# Generated by Django 5.2.7 on 2025-11-23 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subjectrequest',
            name='color',
            field=models.CharField(choices=[('#006DB9', 'Azul Principal'), ('#87A9E0', 'Azul Pastel'), ('#003366', 'Azul Secundario'), ('#FF8C00', 'Naranja EIWA'), ('#FFB84D', 'Naranja Pastel'), ('#28a745', 'Verde'), ('#dc3545', 'Rojo'), ('#6f42c1', 'Morado'), ('#fd7e14', 'Naranja'), ('#20c997', 'Verde Agua'), ('#e83e8c', 'Rosa'), ('#17a2b8', 'Cyan')], default='#006DB9', max_length=7),
        ),
    ]
