# Generated by Django 5.2.7 on 2026-02-01 17:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0002_alter_subjectrequest_color'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Máximo 50 caracteres', max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50)], verbose_name='Nombre de la materia'),
        ),
        migrations.AlterField(
            model_name='subjectrequest',
            name='name',
            field=models.CharField(help_text='Máximo 50 caracteres', max_length=50, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(50)], verbose_name='Nombre de la materia'),
        ),
    ]
