# Generated by Django 5.2.7 on 2026-02-01 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0003_alter_subject_name_alter_subjectrequest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='Máximo 40 caracteres', max_length=40, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(40)], verbose_name='Nombre de la materia'),
        ),
        migrations.AlterField(
            model_name='subjectrequest',
            name='name',
            field=models.CharField(help_text='Máximo 40 caracteres', max_length=40, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(40)], verbose_name='Nombre de la materia'),
        ),
    ]
