# Generated by Django 5.2.7 on 2026-02-01 17:36

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subjects', '0004_alter_subject_name_alter_subjectrequest_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(help_text='2-40 caracteres, letras, números y guiones', max_length=40, validators=[apps.accounts.validators.validate_subject_name], verbose_name='Nombre de la materia'),
        ),
        migrations.AlterField(
            model_name='subjectrequest',
            name='name',
            field=models.CharField(help_text='2-40 caracteres, letras, números y guiones', max_length=40, validators=[apps.accounts.validators.validate_subject_name], verbose_name='Nombre de la materia'),
        ),
    ]
