# Generated by Django 5.2.7 on 2025-11-23 02:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre del grupo')),
                ('description', models.TextField(blank=True, verbose_name='Descripción')),
                ('max_members', models.IntegerField(default=50, verbose_name='Máximo de estudiantes')),
                ('invite_code', models.CharField(max_length=10, unique=True, verbose_name='Código de invitación')),
                ('entry_type', models.CharField(choices=[('free', 'Ingreso Libre'), ('approval', 'Ingreso con Aprobación')], default='approval', max_length=20)),
                ('is_invite_active', models.BooleanField(default=True, verbose_name='Código activo')),
                ('task_create_permission', models.CharField(choices=[('all', 'Todos pueden crear'), ('leader', 'Solo líder'), ('approval', 'Todos, pero requiere aprobación')], default='all', max_length=20)),
                ('task_edit_permission', models.CharField(choices=[('all', 'Todos pueden editar'), ('leader', 'Solo líder'), ('approval', 'Editar requiere aprobación')], default='leader', max_length=20)),
                ('task_delete_permission', models.CharField(choices=[('leader', 'Solo líder'), ('leader_creator', 'Líder + creador'), ('all', 'Cualquiera')], default='leader', max_length=20)),
                ('task_revert_permission', models.CharField(choices=[('leader', 'Solo líder'), ('leader_creator', 'Líder + creador original')], default='leader', max_length=20)),
                ('subject_permission', models.CharField(choices=[('leader', 'Solo líder'), ('suggest', 'Sugerir (requiere aprobación)'), ('all', 'Todos pueden crear')], default='leader', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Grupo',
                'verbose_name_plural': 'Grupos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('group_created', 'Grupo creado'), ('member_joined', 'Miembro se unió'), ('member_left', 'Miembro salió'), ('member_expelled', 'Miembro expulsado'), ('member_warned', 'Advertencia dada'), ('role_changed', 'Rol cambiado'), ('settings_changed', 'Configuración cambiada'), ('invite_regenerated', 'Código regenerado'), ('task_created', 'Tarea creada'), ('task_edited', 'Tarea editada'), ('task_deleted', 'Tarea eliminada'), ('task_reverted', 'Cambio revertido'), ('subject_created', 'Materia creada'), ('subject_deleted', 'Materia eliminada')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='groups.group')),
                ('target_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='targeted_activities', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='group_activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Actividad de Grupo',
                'verbose_name_plural': 'Actividades de Grupos',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GroupMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('leader', 'Líder'), ('co_leader', 'Co-líder'), ('member', 'Miembro')], default='member', max_length=20)),
                ('warnings', models.IntegerField(default=0, verbose_name='Advertencias')),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Miembro de Grupo',
                'verbose_name_plural': 'Miembros de Grupos',
                'ordering': ['role', '-joined_at'],
                'unique_together': {('group', 'user')},
            },
        ),
        migrations.CreateModel(
            name='JoinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pendiente'), ('approved', 'Aprobada'), ('rejected', 'Rechazada')], default='pending', max_length=20)),
                ('message', models.TextField(blank=True, verbose_name='Mensaje opcional')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to='groups.group')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_requests', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='join_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Solicitud de Ingreso',
                'verbose_name_plural': 'Solicitudes de Ingreso',
                'ordering': ['-created_at'],
                'unique_together': {('group', 'user')},
            },
        ),
    ]
