# Generated by Django 5.2.7 on 2025-11-23 02:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupactivity',
            name='activity_type',
            field=models.CharField(choices=[('group_created', 'Grupo creado'), ('member_joined', 'Miembro se unió'), ('member_left', 'Miembro salió'), ('member_removed', 'Miembro expulsado'), ('member_banned', 'Miembro baneado'), ('member_unbanned', 'Miembro desbaneado'), ('member_warned', 'Advertencia dada'), ('role_changed', 'Rol cambiado'), ('settings_changed', 'Configuración cambiada'), ('invite_regenerated', 'Código regenerado'), ('task_created', 'Tarea creada'), ('task_edited', 'Tarea editada'), ('task_deleted', 'Tarea eliminada'), ('task_reverted', 'Cambio revertido'), ('subject_created', 'Materia creada'), ('subject_deleted', 'Materia eliminada')], max_length=30),
        ),
        migrations.CreateModel(
            name='BannedUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(blank=True, verbose_name='Razón del baneo')),
                ('banned_at', models.DateTimeField(auto_now_add=True)),
                ('banned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='banned_users', to=settings.AUTH_USER_MODEL)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_users', to='groups.group')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='banned_from_groups', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Usuario Baneado',
                'verbose_name_plural': 'Usuarios Baneados',
                'ordering': ['-banned_at'],
                'unique_together': {('group', 'user')},
            },
        ),
    ]
