# Generated by Django 5.2.7 on 2025-11-24 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_alter_groupactivity_activity_type_banneduser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='task_edit_permission',
            field=models.CharField(choices=[('all', 'Todos pueden editar'), ('leader', 'Solo líder'), ('approval', 'Editar requiere aprobación del líder'), ('approval_leader_creator', 'Editar requiere aprobación del líder o creador')], default='leader', max_length=30),
        ),
    ]
