# Generated by Django 5.2.7 on 2025-12-10 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_alter_group_task_edit_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='content_moderation',
            field=models.CharField(choices=[('off', 'Desactivada'), ('censor', 'Censurar palabras (###)'), ('block', 'Bloquear contenido')], default='censor', max_length=20, verbose_name='Moderación de contenido'),
        ),
    ]
