# Generated by Django 5.2.7 on 2026-02-07 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0004_group_content_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='document_upload_permission',
            field=models.CharField(choices=[('all', 'Todos pueden subir'), ('leader', 'Solo líder'), ('approval', 'Todos, pero requiere aprobación')], default='all', max_length=20, verbose_name='Permisos de subida de documentos'),
        ),
        migrations.AddField(
            model_name='group',
            name='documents_enabled',
            field=models.BooleanField(default=False, verbose_name='Habilitar documentos'),
        ),
    ]
