# Generated by Django 5.2.7 on 2026-02-01 17:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_apellido_alter_user_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apellido',
            field=models.CharField(help_text='Máximo 30 caracteres', max_length=30, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(30)]),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(help_text='Máximo 30 caracteres', max_length=30, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(30)]),
        ),
    ]
