# Generated by Django 5.2.7 on 2026-02-01 17:36

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_apellido_alter_user_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apellido',
            field=models.CharField(help_text='Solo letras, 2-20 caracteres, máximo 2 letras iguales seguidas', max_length=20, validators=[apps.accounts.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(help_text='Solo letras, 2-20 caracteres, máximo 2 letras iguales seguidas', max_length=20, validators=[apps.accounts.validators.validate_name]),
        ),
    ]
