# Generated by Django 5.2.7 on 2026-02-01 17:43

import apps.accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_apellido_alter_user_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='apellido',
            field=models.CharField(help_text='1-2 apellidos, 3-30 caracteres total, solo letras', max_length=30, validators=[apps.accounts.validators.validate_name]),
        ),
        migrations.AlterField(
            model_name='user',
            name='nombre',
            field=models.CharField(help_text='1-2 nombres, 3-30 caracteres total, solo letras', max_length=30, validators=[apps.accounts.validators.validate_name]),
        ),
    ]
