# Generated by Django 5.2.7 on 2026-02-03 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_user_apellido_alter_user_nombre'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='completed_range',
            field=models.CharField(choices=[('today', 'Hoy'), ('week', 'Esta semana'), ('month', 'Este mes'), ('all', 'Todas')], default='week', max_length=10, verbose_name='Rango de tareas completadas'),
        ),
        migrations.AddField(
            model_name='user',
            name='overdue_range',
            field=models.CharField(choices=[('today', 'Hoy'), ('7days', 'Últimos 7 días'), ('30days', 'Últimos 30 días'), ('all', 'Todas')], default='7days', max_length=10, verbose_name='Rango de tareas vencidas'),
        ),
        migrations.AddField(
            model_name='user',
            name='pending_range',
            field=models.CharField(choices=[('today', 'Hoy'), ('week', 'Esta semana'), ('month', 'Este mes'), ('all', 'Todas')], default='week', max_length=10, verbose_name='Rango de tareas pendientes'),
        ),
    ]
