# Generated by Django 5.2.7 on 2026-02-05 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_multigroup_mode_user_last_active_group'),
        ('groups', '0004_group_content_moderation'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dashboard_groups',
            field=models.ManyToManyField(blank=True, help_text='Grupos que se mostrarán en las estadísticas del dashboard. Si está vacío, se muestran todos.', related_name='dashboard_users', to='groups.group', verbose_name='Grupos visibles en dashboard'),
        ),
        migrations.AlterField(
            model_name='user',
            name='multigroup_mode',
            field=models.CharField(choices=[('separated', 'Mantener grupos separados'), ('unified', 'Unificar todos los grupos')], default='unified', max_length=10, verbose_name='Modo de visualización multigrupo'),
        ),
    ]
