# Generated by Django 5.2.7 on 2026-02-06 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_user_dashboard_groups_alter_user_multigroup_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_bg_color',
            field=models.CharField(blank=True, help_text='Color en formato hexadecimal (#RRGGBB)', max_length=7, null=True, verbose_name='Color de fondo del avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_style',
            field=models.CharField(blank=True, choices=[('smile', 'Sonrisa'), ('cat', 'Gato'), ('star-eyes', 'Ojos de Estrella'), ('robot', 'Robot'), ('heart', 'Corazón'), ('glasses', 'Lentes'), ('music', 'Música'), ('wink', 'Guiño'), ('cool', 'Cool'), ('bear', 'Oso'), ('lightning', 'Rayo'), ('flower', 'Flor'), ('alien', 'Alien'), ('crown', 'Corona'), ('ninja', 'Ninja'), ('party', 'Fiesta')], help_text='Diseño del avatar personalizado', max_length=20, null=True, verbose_name='Estilo de avatar'),
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_svg_color',
            field=models.CharField(blank=True, help_text='Color en formato hexadecimal (#RRGGBB)', max_length=7, null=True, verbose_name='Color del diseño del avatar'),
        ),
    ]
