# Generated by Django 5.2.7 on 2026-02-06 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_user_avatar_bg_color_user_avatar_style_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar_category',
            field=models.CharField(default='eiwa', help_text='Categoría del avatar (eiwa, animals, disney)', max_length=20, verbose_name='Categoría de avatar'),
        ),
    ]
