# Generated by Django 5.2.7 on 2026-02-03 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_taskcompletion'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='archived_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('pending', 'Pendiente'), ('overdue_recent', 'Vencida reciente'), ('completed', 'Completada'), ('archived', 'Archivada')], default='pending', max_length=20),
        ),
    ]
