# Generated by Django 5.2.7 on 2026-02-07 02:16

import apps.tasks.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0005_task_archived_at_alter_task_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.tasks.models.task_attachment_upload_to, verbose_name='Archivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('file_size', models.IntegerField(verbose_name='Tamaño (bytes)')),
                ('file_type', models.CharField(max_length=100, verbose_name='Tipo de archivo')),
                ('status', models.CharField(choices=[('pending', 'Pendiente de aprobación'), ('approved', 'Aprobado'), ('rejected', 'Rechazado')], default='approved', max_length=20)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_attachments', to=settings.AUTH_USER_MODEL)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tasks.task')),
                ('uploaded_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Archivo Adjunto',
                'verbose_name_plural': 'Archivos Adjuntos',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
