# Generated by Django 5.2.7 on 2026-02-07 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_taskattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskrequest',
            name='attachments_info',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='taskrequest',
            name='has_attachments',
            field=models.BooleanField(default=False),
        ),
    ]
