# Generated by Django 5.2.7 on 2026-02-07 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0007_taskrequest_attachments_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskattachment',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de eliminación física'),
        ),
        migrations.AddField(
            model_name='taskattachment',
            name='file_deleted',
            field=models.BooleanField(default=False, verbose_name='Archivo físico eliminado'),
        ),
    ]
