# Generated by Django 5.2.7 on 2026-02-07 03:23

import apps.tasks.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0008_taskattachment_deleted_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskrequest',
            name='attachments_info',
        ),
        migrations.RemoveField(
            model_name='taskrequest',
            name='has_attachments',
        ),
        migrations.CreateModel(
            name='TaskRequestAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.tasks.models.task_request_attachment_upload_to, verbose_name='Archivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('file_size', models.IntegerField(verbose_name='Tamaño (bytes)')),
                ('file_type', models.CharField(max_length=100, verbose_name='Tipo de archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('task_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_attachments', to='tasks.taskrequest')),
            ],
            options={
                'verbose_name': 'Archivo de Solicitud',
                'verbose_name_plural': 'Archivos de Solicitudes',
            },
        ),
    ]
