# Generated by Django 5.2.7 on 2026-02-07 03:28

import apps.tasks.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0009_remove_taskrequest_attachments_info_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskeditrequest',
            name='documents_to_delete',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TaskEditAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=apps.tasks.models.task_edit_attachment_upload_to, verbose_name='Archivo')),
                ('original_filename', models.CharField(max_length=255, verbose_name='Nombre original')),
                ('file_size', models.IntegerField(verbose_name='Tamaño (bytes)')),
                ('file_type', models.CharField(max_length=100, verbose_name='Tipo de archivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('edit_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='new_attachments', to='tasks.taskeditrequest')),
            ],
            options={
                'verbose_name': 'Archivo Nuevo en Edición',
                'verbose_name_plural': 'Archivos Nuevos en Ediciones',
            },
        ),
    ]
